name: Track Unfollowers

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC time

jobs:
  track-unfollowers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Track Unfollowers Script
      run: |
        python unfollowers.py
